//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Gender { get; set; }
        public string PrimaryColor { get; set; }
        public string SecondaryColor { get; set; }
        public string Breed { get; set; }
        public bool Friendly { get; set; }
        public bool EarTipped { get; set; }
        public bool DeClawed { get; set; }
        public bool MicroChipped { get; set; }
        public bool SpayedNeutered { get; set; }
        public bool Vaccinated { get; set; }
        public string Comments { get; set; }
        public string Photo { get; set; }
        public string ColonyBorough { get; set; }
        public string ColonyNeighborhood { get; set; }
        public string ColonyCaretakerName { get; set; }
        public string ColonyCaretakerPhone { get; set; }
    }
}
